// <auto-generated />
using System;
using Estoque.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Estoque.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(EstoqueDbContext))]
    [Migration("20260616225615_AdicionaEventosProcessados")]
    partial class AdicionaEventosProcessados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Estoque.Domain.Entidades.EntradaEstoque", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("dataEntrada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_entrada");

                    b.Property<string>("numeroNotaFiscal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_nota_fiscal");

                    b.Property<Guid>("produtoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<int>("quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.HasKey("id");

                    b.ToTable("entradas_estoque", (string)null);
                });

            modelBuilder.Entity("Estoque.Domain.Entidades.ItemEstoque", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("produtoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<int>("quantidadeDisponivel")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_disponivel");

                    b.Property<DateTime>("ultimaAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_atualizacao");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("id");

                    b.HasIndex("produtoId")
                        .IsUnique();

                    b.ToTable("itens_estoque", (string)null);
                });

            modelBuilder.Entity("Estoque.Infrastructure.Persistencia.Idempotencia.EventoProcessado", b =>
                {
                    b.Property<Guid>("idEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_evento");

                    b.Property<string>("motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<DateTime>("processadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em");

                    b.Property<bool>("rejeitado")
                        .HasColumnType("boolean")
                        .HasColumnName("rejeitado");

                    b.HasKey("idEvento");

                    b.ToTable("eventos_processados", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
